export const SkillStack = [
  { sources: "./express.png", alt: "Express Js" },
  { sources: "./ts.png", alt: "TypeScript" },
  { sources: "./tailwind.png", alt: "Tailwind" },
  { sources: "./postgre.png", alt: "PostgreSql" },
  { sources: "./prism.png", alt: "Prisma" },
  { sources: "./stripe.png", alt: "Stripe" },
  { sources: "./next.png", alt: "NEXT JS" },
  { sources: "./gsap-greensock.png", alt: "Gsap" },
  { sources: "./mongodb.png", alt: "MongoDB" },
  { sources: "./logo vite.png", alt: "Vite" },
  { sources: "./nestjsicon.png", alt: "NestJS" },
  { sources: "./react.png", alt: "React Js" },
  { sources: "./reactquery.png", alt: "ReactQuery" },
  { sources: "./js.png", alt: "Javascript" },
  { sources: "./shadcn logo.png", alt: "Shadcn" },
  { sources: "./node-js.png", alt: "Node Js" },
  { sources: "./css.png", alt: "CSS" },
  { sources: "./html.png", alt: "HTML" },
];
